import {
  LayoutDashboard,
  BookOpen,
  Calendar,
  ClipboardList,
  FileText,
  GraduationCap,
  CreditCard,
  Library,
  Home,
  Users,
  BarChart3,
  CheckSquare,
  DollarSign,
  Building2,
  UserCheck,
  Award,
  Settings,
  BookMarked,
  ScrollText,
} from 'lucide-react'

export const NAV = {
  student: [
    { label: 'Dashboard',   to: 'dashboard',   icon: LayoutDashboard },
    { label: 'My Courses',  to: 'courses',     icon: BookOpen },
    { label: 'Timetable',   to: 'timetable',   icon: Calendar },
    { label: 'Attendance',  to: 'attendance',  icon: CheckSquare },
    { label: 'Assignments', to: 'assignments', icon: ClipboardList },
    { label: 'Exams',       to: 'exams',       icon: FileText },
    { label: 'Grades',      to: 'grades',      icon: GraduationCap },
    { label: 'Payments',    to: 'payments',    icon: CreditCard },
    { label: 'Library',     to: 'library',     icon: Library },
    { label: 'Hostel',      to: 'hostel',      icon: Home },
  ],
  applicant: [
    { label: 'Dashboard',   to: 'dashboard',   icon: LayoutDashboard },
    { label: 'Application', to: 'application', icon: FileText },
  ],
  lecturer: [
    { label: 'Dashboard',   to: 'dashboard',   icon: LayoutDashboard },
    { label: 'My Courses',  to: 'courses',     icon: BookOpen },
    { label: 'Attendance',  to: 'attendance',  icon: CheckSquare },
    { label: 'Assignments', to: 'assignments', icon: ClipboardList },
    { label: 'Grades',      to: 'grades',      icon: GraduationCap },
    { label: 'Timetable',   to: 'timetable',   icon: Calendar },
  ],
  hod: [
    { label: 'Dashboard',       to: 'dashboard',  icon: LayoutDashboard },
    { label: 'Courses',         to: 'courses',    icon: BookOpen },
    { label: 'Attendance',      to: 'attendance', icon: CheckSquare },
    { label: 'Score Approval',  to: 'scores',     icon: GraduationCap },
    { label: 'Staff',           to: 'staff',      icon: Users },
    { label: 'Reports',         to: 'reports',    icon: BarChart3 },
  ],
  dean: [
    { label: 'Dashboard',          to: 'dashboard',   icon: LayoutDashboard },
    { label: 'Departments',        to: 'departments', icon: Building2 },
    { label: 'Score Ratification', to: 'scores',      icon: GraduationCap },
    { label: 'Reports',            to: 'reports',     icon: BarChart3 },
  ],
  registrar: [
    { label: 'Dashboard',          to: 'dashboard',    icon: LayoutDashboard },
    { label: 'Applications',       to: 'applications', icon: FileText },
    { label: 'Students',           to: 'students',     icon: Users },
    { label: 'Registration',       to: 'registration', icon: BookMarked },
    { label: 'Academic Calendar',  to: 'calendar',     icon: Calendar },
  ],
  bursar: [
    { label: 'Dashboard',     to: 'dashboard',  icon: LayoutDashboard },
    { label: 'Fee Schedule',  to: 'fees',       icon: DollarSign },
    { label: 'Payments',      to: 'payments',   icon: CreditCard },
    { label: 'Clearances',    to: 'clearances', icon: UserCheck },
    { label: 'Waivers',       to: 'waivers',    icon: Award },
  ],
  super_admin: [
    { label: 'Dashboard',  to: 'dashboard', icon: LayoutDashboard },
    { label: 'Structure',  to: 'structure', icon: Building2 },
    { label: 'Users',      to: 'users',     icon: Users },
    { label: 'Sessions',   to: 'sessions',  icon: Calendar },
    { label: 'Grading',    to: 'grading',   icon: GraduationCap },
    { label: 'Settings',   to: 'settings',  icon: Settings },
  ],
  alumni: [
    { label: 'Dashboard',   to: 'dashboard',  icon: LayoutDashboard },
    { label: 'Transcript',  to: 'transcript', icon: ScrollText },
    { label: 'Directory',   to: 'directory',  icon: Users },
  ],
}
