"""add exam_slots table

Revision ID: a9ede2cf3577
Revises: ae9f4214d081
Create Date: 2026-05-30 11:22:35.278331+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9ede2cf3577'
down_revision: Union[str, None] = 'ae9f4214d081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('invigilator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invigilator_id'], ['users.id'], name='exam_slots_invigilator_id_fkey'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], name='exam_slots_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_slots_pkey'),
    sa.UniqueConstraint('section_id', 'date', name='exam_slots_section_id_date_key')
    )
    # ### end Alembic commands ###
