"""add exam_slots table

Revision ID: 1a1d18c6d7e2
Revises: a9ede2cf3577
Create Date: 2026-05-30 11:49:36.638457+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1d18c6d7e2'
down_revision: Union[str, None] = 'a9ede2cf3577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
