"""add server default now to timestamp columns

Revision ID: 6b2a6f428747
Revises: 1a1d18c6d7e2
Create Date: 2026-05-30 12:13:17.689985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2a6f428747'
down_revision: Union[str, None] = '1a1d18c6d7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
