"""Initial database migration

Revision ID: ff323f97b83c
Revises: 
Create Date: 2026-07-23 17:02:28.195892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff323f97b83c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('is_main_campus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('campus_id')
    )
    op.create_table('persons',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('building_name', sa.String(length=20), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('LECTURE_HALL', 'LAB', 'SEMINAR_ROOM', name='roomtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('semesters',
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_start', sa.Date(), nullable=False),
    sa.Column('registration_end', sa.Date(), nullable=False),
    sa.Column('grading_deadline', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_table('faculties',
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('dean_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dean_id'], ['staffs.staff_id'], name='fk_faculties_dean_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_index(op.f('ix_faculties_campus_id'), 'faculties', ['campus_id'], unique=False)
    op.create_index(op.f('ix_faculties_dean_id'), 'faculties', ['dean_id'], unique=False)
    op.create_table('account_roles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'REGISTRAR', 'FINANCE', 'ADMIN', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'role')
    )
    op.create_table('audit-logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('target_entity_type', sa.String(length=20), nullable=False),
    sa.Column('target_entity_id', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit-logs_actor_user_id'), 'audit-logs', ['actor_user_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('hod_id', sa.Uuid(), nullable=True),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.faculty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hod_id'], ['staffs.staff_id'], name='fk_departments_hod_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_departments_hod_id'), 'departments', ['hod_id'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_table('programs',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('degree_level', sa.Enum('UNDERGRADUATE', 'MASTERS', 'DOCTORATE', name='degreelevel'), nullable=False),
    sa.Column('total_credits_required', sa.Integer(), nullable=False),
    sa.Column('duration_terms', sa.Integer(), nullable=False),
    sa.Column('olevel_subjects_required', sa.JSON(), nullable=False),
    sa.Column('jamb_subjects_required', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index(op.f('ix_programs_department_id'), 'programs', ['department_id'], unique=False)
    op.create_table('staffs',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Enum('L1', 'L2', 'L3', name='rank'), nullable=False),
    sa.Column('employment_status', sa.Enum('FULL_TIME', 'PART_TIME', 'ADJUNCT', name='employmentstatus'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staffs_department_id'), 'staffs', ['department_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('state_of_origin', sa.String(length=20), nullable=False),
    sa.Column('lga_of_origin', sa.String(length=20), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('jamb_registration_number', sa.String(length=20), nullable=False),
    sa.Column('jamb_scores', sa.JSON(), nullable=False),
    sa.Column('jamb_total_scores', sa.Integer(), nullable=False),
    sa.Column('jamb_entry_route', sa.Enum('UTME', 'DIRECT_ENTRY', name='entryroute'), nullable=False),
    sa.Column('olevel_gradess', sa.JSON(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('first_choice_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_indegene', sa.Boolean(), nullable=False),
    sa.Column('iivc_verification_status', sa.Enum('NOT_APPLICABLE', 'PENDING', 'VERIFIED', 'REJECTED', name='iivcverificationstatus'), nullable=False),
    sa.Column('screening_status', sa.Enum('PENDING', 'SCREENED', 'ADMITTED', 'REJECTED', 'WAITLISTED', name='screeningstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_program_id'), 'applications', ['program_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('course_sections',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('lecturer_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['staffs.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_course_sections_course_id'), 'course_sections', ['course_id'], unique=True)
    op.create_index(op.f('ix_course_sections_lecturer_id'), 'course_sections', ['lecturer_id'], unique=False)
    op.create_index(op.f('ix_course_sections_semester_id'), 'course_sections', ['semester_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('matric_number', sa.String(length=9), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('enrollment_status', sa.Enum('ACTIVE', 'SUSPENDED', 'GRADUATED', 'WITHDRAWN', name='enrollmentstatus'), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('entry_year', sa.String(length=10), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('national_id_number', sa.String(length=11), nullable=False),
    sa.Column('contact_address', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact', sa.String(length=100), nullable=False),
    sa.Column('indigene_status', sa.Enum('INDIGENE', 'NON_INDIGENE', name='indigenestatus'), nullable=False),
    sa.Column('admission_stream', sa.Enum('STREAM_1', 'STREAM_2', name='admissionstream'), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_students_application_id'), 'students', ['application_id'], unique=False)
    op.create_index(op.f('ix_students_campus_id'), 'students', ['campus_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_status', sa.Enum('ENROLLED', 'WAITLISTED', 'DROPPED', 'COMPLETED', name='enrolmentstatus'), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('override_flag', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_enrollments_section_id'), 'enrollments', ['section_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'PARTIAL', name='status'), nullable=False),
    sa.Column('fee_structure_type', sa.Enum('STREAM_1', 'STREAM_2', name='feestructuretype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_semester_id'), 'invoices', ['semester_id'], unique=False)
    op.create_index(op.f('ix_invoices_student_id'), 'invoices', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('letter_grade', sa.String(length=1), nullable=False),
    sa.Column('grade_points', sa.Float(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('revision_approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ),
    sa.ForeignKeyConstraint(['revision_approved_by'], ['staffs.staff_id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['staffs.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_index(op.f('ix_grades_enrollment_id'), 'grades', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_grades_submitted_by'), 'grades', ['submitted_by'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('gateway_transaction_ref', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_grades_submitted_by'), table_name='grades')
    op.drop_index(op.f('ix_grades_enrollment_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_invoices_student_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_semester_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_section_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_students_campus_id'), table_name='students')
    op.drop_index(op.f('ix_students_application_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_course_sections_semester_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_lecturer_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_course_id'), table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_applications_program_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_staffs_department_id'), table_name='staffs')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_programs_department_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_departments_hod_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit-logs_actor_user_id'), table_name='audit-logs')
    op.drop_table('audit-logs')
    op.drop_table('account_roles')
    op.drop_index(op.f('ix_faculties_dean_id'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_campus_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('semesters')
    op.drop_table('rooms')
    op.drop_table('persons')
    op.drop_table('campuses')
    # ### end Alembic commands ###
